[package]
name = "m68k_reloaded_common"
version = "0.1.0"
authors = ["Marcel Garus <marcel.garus@gmail.com>"]
edition = "2018"

[lib]
name = "m68k_reloaded_common"
path = "src/lib.rs"

[[bin]]
name = "common"
path = "src/main.rs"

[dependencies]
